name: Basic App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Install nodejs
        run: sudo apk add --update nodejs npm

      - name: Install depenendencies
        run: cd ~/code/ && npm install

      - name: Check Yarn version
        run: yarn -v

  test:
    steps:
      - name: Test App
        run: echo "testing app ..."

  deploy:
    steps:
      - name: Deploy App
        run: echo "deploying app ..."
