name: Basic App Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    steps:
      # - name: Install curl
      #   run: sudo apt install -y curl

      # - name: Add nodejs source
      #   run: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh
      #   directory: /home/ubuntu/

      # - name: Install nodejs
      #   run: sudo apt install nodejs

      - name: Install dependencies
        run: export PATH="/home/ubuntu/.global_npm/bin:$PATH" && yarn

  test:
    steps:
      - name: Test App
        run: echo "testing app ..."

  deploy:
    steps:
      - name: Deploy App
        run: echo "deploying app ..."
