name: Basic App Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    steps:
      - name: Install curl
        run: sudo apt install -y curl

      - name: Add nodejs source
        run: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh
        directory: /home/ubuntu/

      - name: Install nodejs
        run: sudo apt install nodejs

      - name: Show $PATH
        run: echo $PATH

      # - name: Build App
      #   run: NODE_OPTIONS=--max_old_space_size=8192 npm i
      - name: Install dependencies
        run: yarn

  test:
    steps:
      - name: Test App
        run: echo "testing app ..."

  deploy:
    steps:
      - name: Deploy App
        run: echo "deploying app ..."
