name: Basic App Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    steps:
      - name: Add nodejs source
        run: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh
        directory: /home/ubuntu/

      - name: Install nodejs
        run: sudo apt install nodejs

      - name: Build App
        run: npm install

  test:
    steps:
      - name: Test App
        run: echo "testing app ..."

  deploy:
    steps:
      - name: Deploy App
        run: echo "deploying app ..."
